# Generated by Django 2.0.1 on 2018-02-07 14:45

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_custom_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True),
        ),
    ]
