# Generated by Django 2.0.1 on 2018-02-15 17:01

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180215_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=filebrowser.fields.FileBrowseField(blank=True, help_text='Will be copied from the original event if you use the clone feature.', max_length=200, null=True),
        ),
    ]
