# Generated by Django 2.0.1 on 2018-01-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_imagegallery_imageingallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name_plural': 'Image galleries'},
        ),
        migrations.AlterModelOptions(
            name='imageingallery',
            options={'ordering': ('order',), 'verbose_name_plural': 'Images in gallery'},
        ),
        migrations.AddField(
            model_name='imageingallery',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
