# Generated by Django 2.0.1 on 2018-01-12 16:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20180112_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=65535),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
