# Generated by Django 2.0.1 on 2018-01-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='display_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='list_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
