# Generated by Django 2.0.1 on 2018-01-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20180116_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='display_list',
        ),
    ]
