# Generated by Django 2.0.1 on 2018-01-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_auto_20180117_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='list_style',
            field=models.CharField(choices=[('NONE', 'None'), ('VERTICALSEP', 'Vertical separators'), ('HORIZONTALSEP', 'Horizontal separator on top'), ('VERTICALHORIZONTAL', 'Vertical + horizontal separator')], default='None', max_length=13),
        ),
    ]
