# Generated by Django 2.0.1 on 2018-01-17 15:01

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_auto_20180117_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='photo',
        ),
        migrations.AddField(
            model_name='speaker',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imageingallery',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True),
        ),
    ]
