# Generated by Django 2.0.1 on 2018-01-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonInModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Button')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Module')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Module',
            },
        ),
    ]
