# Generated by Django 2.0.1 on 2018-01-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_buttoninmodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttoninmodule',
            name='button',
        ),
        migrations.RemoveField(
            model_name='buttoninmodule',
            name='module',
        ),
        migrations.AddField(
            model_name='button',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Module'),
        ),
        migrations.AddField(
            model_name='button',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.DeleteModel(
            name='ButtonInModule',
        ),
    ]
