# Generated by Django 2.0.1 on 2018-01-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_auto_20180117_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonInModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Module',
            },
        ),
        migrations.RemoveField(
            model_name='button',
            name='module',
        ),
        migrations.RemoveField(
            model_name='button',
            name='order',
        ),
        migrations.AddField(
            model_name='buttoninmodule',
            name='button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Button'),
        ),
        migrations.AddField(
            model_name='buttoninmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Module'),
        ),
    ]
