# Generated by Django 2.0.1 on 2018-01-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_imageingallery_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Module')),
            ],
            options={
                'verbose_name_plural': 'Video galleries',
            },
            bases=('content.module',),
        ),
        migrations.CreateModel(
            name='VideoInGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.VideoGallery')),
            ],
            options={
                'verbose_name_plural': 'Videos in gallery',
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('SPONSOR', 'Sponsorship'), ('IMAGEGALLERY', 'Image gallery'), ('VIDEOGALLERY', 'Video gallery')], max_length=12, null=True),
        ),
    ]
