# Generated by Django 2.0.1 on 2018-01-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_auto_20180119_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='content_justify',
            field=models.CharField(choices=[('LEFT', 'Left'), ('CENTER', 'Center'), ('RIGHT', 'Right')], default='LEFT', max_length=6),
        ),
    ]
