# Generated by Django 2.0.1 on 2018-03-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20180314_1906'),
        ('sites', '0002_alter_domain_unique'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_js', models.TextField(blank=True, help_text="Printed just before the closing </head> tag. Make sure it's an async script. It will be rendered as-is, unescaped, so make sure its coming from a trusted source.", null=True, verbose_name='Custom JS')),
                ('home_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Site',
            },
        ),
        migrations.AlterField(
            model_name='redirecthost',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_hosts', to='domains.CustomSite'),
        ),
    ]
