# Generated by Django 2.0.1 on 2018-03-19 17:38
from django.contrib.sites.models import Site
from django.db import migrations

from domains.models import CustomSite


def gen_customsites(apps, schema_editor):
    sites = Site.objects.all()
    for site in sites:
        CustomSite.objects.get_or_create(site_ptr_id=site.id, domain=site.domain, name=site.name)

class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_customsite'),
    ]

    operations = [
        migrations.RunPython(gen_customsites)
    ]
