# Generated by Django 2.0.1 on 2018-03-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_customsite_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsite',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_site', to='sites.Site'),
        ),
    ]
