# Generated by Django 2.0.1 on 2018-03-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('domains', '0004_sitesettings_custom_css'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='base_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site', verbose_name='Clone from'),
        ),
    ]
