# Generated by Django 2.0.1 on 2018-03-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_auto_20180328_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='base_event',
            new_name='base_site',
        ),
    ]
