# Generated by Django 2.0.1 on 2018-03-28 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0012_auto_20180328_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='base_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domains.SiteSettings', verbose_name='Clone from'),
        ),
    ]
