# Generated by Django 2.0.1 on 2018-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0020_auto_20180409_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='remote_url',
            field=models.URLField(default='example.com'),
            preserve_default=False,
        ),
    ]
