# Generated by Django 2.0.1 on 2018-04-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0021_sitesettings_remote_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='redirecthost',
            name='ssh_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='remote_url',
            field=models.URLField(verbose_name='Theme repo URL'),
        ),
    ]
