# Generated by Django 2.0.1 on 2018-04-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0022_auto_20180419_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirecthost',
            old_name='ssh_certified',
            new_name='ssl_certified',
        ),
    ]
