# Generated by Django 2.0.1 on 2018-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0023_auto_20180419_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ssl_certified',
            field=models.BooleanField(default=False),
        ),
    ]
