# Generated by Django 2.0.1 on 2018-01-11 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0013_auto_20180111_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigHeaderMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='Label')),
                ('target_type', models.CharField(choices=[('page', 'Page (select a page below)'), ('url', 'URL (enter one below)')], max_length=255, verbose_name='Link target')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Page')),
            ],
            options={
                'verbose_name_plural': 'Main Menu',
                'verbose_name': 'Main Menu',
                'abstract': False,
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='Label')),
                ('target_type', models.CharField(choices=[('page', 'Page (select a page below)'), ('url', 'URL (enter one below)')], max_length=255, verbose_name='Link target')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Page')),
            ],
            options={
                'verbose_name_plural': 'Footer Menu',
                'verbose_name': 'Footer Menu',
                'abstract': False,
                'ordering': ['order'],
            },
        ),
    ]
