# Generated by Django 2.0.1 on 2018-01-30 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20180122_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigheadermenu',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Page'),
        ),
        migrations.AlterField(
            model_name='footermenu',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Page'),
        ),
    ]
