# Generated by Django 2.0.1 on 2018-02-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_base_event'),
        ('menus', '0003_auto_20180130_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigheadermenu',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bigheadermenus', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footermenu',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='footermenus', to='events.Event'),
            preserve_default=False,
        ),
    ]
