# Generated by Django 2.0.1 on 2018-02-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180215_1701'),
        ('content', '0081_imagegallery_images_per_row'),
        ('menus', '0004_auto_20180201_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='Label')),
                ('target_type', models.CharField(choices=[('page', 'Page (select a page below)'), ('url', 'URL (enter one below)')], max_length=255, verbose_name='Link target')),
                ('url', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialmediamenus', to='events.Event')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Icon')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Page')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': 'Main Menu',
                'abstract': False,
                'verbose_name': 'Main Menu',
            },
        ),
    ]
