# Generated by Django 2.0.1 on 2018-02-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20180220_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigheadermenu',
            name='target_type',
            field=models.CharField(choices=[('page', 'Page (select a page below)'), ('url', 'URL (enter one below)')], default='url', max_length=255, verbose_name='Link target'),
        ),
        migrations.AlterField(
            model_name='footermenu',
            name='target_type',
            field=models.CharField(choices=[('page', 'Page (select a page below)'), ('url', 'URL (enter one below)')], default='url', max_length=255, verbose_name='Link target'),
        ),
        migrations.AlterField(
            model_name='socialmediamenu',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Icon'),
        ),
        migrations.AlterField(
            model_name='socialmediamenu',
            name='target_type',
            field=models.CharField(choices=[('page', 'Page (select a page below)'), ('url', 'URL (enter one below)')], default='url', max_length=255, verbose_name='Link target'),
        ),
    ]
