# Generated by Django 2.0.1 on 2018-02-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_auto_20180220_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediamenu',
            name='icon',
        ),
        migrations.AddField(
            model_name='socialmediamenu',
            name='social_network',
            field=models.CharField(choices=[('fa-twitter', 'Twitter'), ('fa-github', 'GitHub'), ('fa-slack', 'Slack'), ('fa-youtube', 'Youtube'), ('fa-facebook', 'Facebook')], default='fa-twitter', max_length=25),
            preserve_default=False,
        ),
    ]
