# Generated by Django 2.0.1 on 2018-03-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('menus', '0009_auto_20180227_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigheadermenu',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bigheadermenus', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footermenu',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='footermenus', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediamenu',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socialmediamenus', to='sites.Site'),
            preserve_default=False,
        ),
    ]
