# Generated by Django 2.0.1 on 2018-03-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_auto_20180314_1904'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bigheadermenu',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='footermenu',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='socialmediamenu',
            managers=[
            ],
        ),
    ]
