# Generated by Django 2.0.1 on 2018-01-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=30)),
                ('translation', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
