# Generated by Django 2.0.1 on 2018-02-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180223_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('SPONSORSHIP', 'Sponsorship'), ('IMAGEGALLERY', 'Image gallery'), ('VIDEOGALLERY', 'Video gallery'), ('POSTCATEGORY', 'Post category'), ('CUSTOMHTML', 'Custom HTML')], max_length=12, null=True),
        ),
    ]
