# Generated by Django 2.0.1 on 2018-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180111_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image_position',
            field=models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], default='LEFT', max_length=6),
        ),
    ]
