# Generated by Django 2.0.1 on 2018-01-11 18:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20180111_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='content',
            field=tinymce.models.HTMLField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(max_length=65535),
        ),
    ]
