# Generated by Django 2.0.1 on 2018-02-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20180228_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('SPONSORSHIP', 'Sponsorship'), ('IMAGEGALLERY', 'Image gallery'), ('VIDEOGALLERY', 'Video gallery'), ('POSTCATEGORY', 'Post category'), ('CUSTOMHTML', 'Custom HTML'), ('MODULECONTAINER', 'Module container')], max_length=12, null=True),
        ),
    ]
