# Generated by Django 2.0.1 on 2018-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20180228_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='caption',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
