# Generated by Django 2.0.1 on 2018-01-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20180111_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='kicker',
        ),
        migrations.AddField(
            model_name='block',
            name='kicker',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
