# Generated by Django 2.0.1 on 2018-03-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20180301_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='title_only',
            field=models.BooleanField(default=False),
        ),
    ]
