# Generated by Django 2.0.1 on 2018-03-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_module_title_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='title_only',
        ),
        migrations.AddField(
            model_name='block',
            name='title_only',
            field=models.BooleanField(default=False),
        ),
    ]
