# Generated by Django 2.0.1 on 2018-03-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20180302_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('style', models.CharField(choices=[('NONE', 'None'), ('VERTICALSEP', 'Vertical separators'), ('HORIZONTALSEP', 'Horizontal separator on top'), ('VERTICALHORIZONTAL', 'Vertical + horizontal separator'), ('INCOLUMNS', 'Display in two columns')], default='None', max_length=20)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='content.Module')),
            ],
        ),
        migrations.RemoveField(
            model_name='block',
            name='list_style',
        ),
        migrations.RemoveField(
            model_name='block',
            name='list_title',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='module',
        ),
    ]
