# Generated by Django 2.0.1 on 2018-01-12 14:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20180111_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=65535),
        ),
    ]
