# Generated by Django 2.0.1 on 2018-03-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20180312_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='list',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='content.List'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='content.Module'),
        ),
    ]
