# Generated by Django 2.0.1 on 2018-03-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20180312_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='caption',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.List'),
        ),
    ]
