# Generated by Django 2.0.1 on 2018-01-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='page',
        ),
        migrations.AlterField(
            model_name='moduleinpage',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_in_page', to='content.Module'),
        ),
        migrations.AlterField(
            model_name='moduleinpage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_in_page', to='content.Page'),
        ),
    ]
