# Generated by Django 2.0.1 on 2018-03-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20180312_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='caption',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
