# Generated by Django 2.0.1 on 2018-03-12 18:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20180312_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='caption',
            field=tinymce.models.HTMLField(blank=True, max_length=800, null=True),
        ),
    ]
