# Generated by Django 2.0.1 on 2018-01-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20180112_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='module',
            name='content',
        ),
        migrations.RemoveField(
            model_name='module',
            name='font_color',
        ),
        migrations.AddField(
            model_name='module',
            name='image_on_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Style'),
        ),
    ]
