# Generated by Django 2.0.1 on 2018-03-13 17:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_list_display_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tortor metus, pretium et diam sed, feugiat feugiat ligula. Morbi id urna neque. Vivamus egestas mauris a egestas varius. Donec vestibulum nisi odio, non malesuada nisl pellentesque non. Mauris at interdum purus, faucibus molestie justo. Sed id pharetra enim. Vestibulum nec ', max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(max_length=65535, null=True),
        ),
    ]
