# Generated by Django 2.0.1 on 2018-03-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20180313_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('SPONSORSHIP', 'Sponsorship'), ('IMAGEGALLERY', 'Image gallery'), ('VIDEOGALLERY', 'Video gallery'), ('POSTCATEGORY', 'Post category'), ('CUSTOMHTML', 'Custom HTML'), ('MODULECONTAINER', 'Module container')], max_length=20, null=True),
        ),
    ]
