# Generated by Django 2.0.1 on 2018-03-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20180313_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=True, help_text='If unchecked, only logged-in users can see this page'),
        ),
    ]
