# Generated by Django 2.0.1 on 2018-03-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('content', '0022_auto_20180313_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buttoninmodule',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buttoninmodules', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icon',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageingallery',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imageingallerys', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listitems', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduleinmodule',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moduleinmodules', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduleinpage',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moduleinpages', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='sites.Site'),
            preserve_default=False,
        ),
    ]
