# Generated by Django 2.0.1 on 2018-03-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20180314_1904'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='block',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='button',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='buttoninmodule',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customhtml',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='icon',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='imagegallery',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='imageingallery',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='list',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='listitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='module',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='modulecontainer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='moduleinmodule',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='moduleinpage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='postcategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sponsorship',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='style',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='videogallery',
            managers=[
            ],
        ),
    ]
