# Generated by Django 2.0.1 on 2018-01-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20180115_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='layout',
        ),
        migrations.AddField(
            model_name='module',
            name='layout',
            field=models.CharField(choices=[('ONECOL', 'One column'), ('TWOCOL', 'Two columns')], default='ONECOL', max_length=6),
        ),
    ]
