# Generated by Django 2.0.1 on 2018-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20180116_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='layout',
        ),
        migrations.AddField(
            model_name='block',
            name='layout',
            field=models.CharField(choices=[('ONECOL', 'One column'), ('TWOCOL', 'Two columns')], default='ONECOL', max_length=6),
        ),
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('SPONSOR', 'Sponsorship'), ('IMAGEGALLERY', 'Image gallery')], max_length=12, null=True),
        ),
    ]
