# Generated by Django 2.0.1 on 2018-03-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20180314_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='style',
            new_name='list_style',
        ),
    ]
