# Generated by Django 2.0.1 on 2018-04-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20180403_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinmodule',
            name='module',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='content.Module'),
        ),
    ]
