# Generated by Django 2.0.1 on 2018-01-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20180116_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
