# Generated by Django 2.0.1 on 2018-04-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20180403_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttoninmodule',
            name='button',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.Button'),
        ),
        migrations.AlterField(
            model_name='buttoninmodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='content.Module'),
        ),
        migrations.AlterField(
            model_name='imageingallery',
            name='imagegallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.ImageGallery'),
        ),
        migrations.AlterField(
            model_name='list',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='content.Module'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.List'),
        ),
        migrations.AlterField(
            model_name='moduleinmodule',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulesinmodule', to='content.ModuleContainer'),
        ),
        migrations.AlterField(
            model_name='moduleinpage',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_in_page', to='content.Module'),
        ),
        migrations.AlterField(
            model_name='moduleinpage',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_in_page', to='content.Page'),
        ),
    ]
