# Generated by Django 2.0.1 on 2018-01-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_module_content_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='content_width',
            field=models.CharField(choices=[('WIDE', 'Wide'), ('NARROW', 'Narrow')], default='WIDE', max_length=6),
        ),
    ]
