# Generated by Django 2.0.1 on 2018-04-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20180405_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinmodule',
            name='module',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='content.Module'),
        ),
    ]
