# Generated by Django 2.0.1 on 2018-01-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_auto_20180117_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageingallery',
            name='as_circle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buttoninmodule',
            name='button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.Button'),
        ),
        migrations.AlterField(
            model_name='buttoninmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='content.Module'),
        ),
    ]
