# Generated by Django 2.0.1 on 2018-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_auto_20180119_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageingallery',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
