# Generated by Django 2.0.1 on 2018-01-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_block_content_justify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
    ]
