# Generated by Django 2.0.1 on 2018-01-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_auto_20180122_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
