# Generated by Django 2.0.1 on 2018-01-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_auto_20180122_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='talk',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
