# Generated by Django 2.0.1 on 2018-01-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_auto_20180130_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='start_time',
            new_name='start',
        ),
    ]
