# Generated by Django 2.0.1 on 2018-01-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_auto_20180130_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
