# Generated by Django 2.0.1 on 2018-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0060_talk_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
