# Generated by Django 2.0.1 on 2018-01-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0062_auto_20180130_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
