# Generated by Django 2.0.1 on 2018-01-30 18:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0063_auto_20180130_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=65535),
        ),
    ]
