# Generated by Django 2.0.1 on 2018-01-30 18:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0064_auto_20180130_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, max_length=65535),
        ),
    ]
