# Generated by Django 2.0.1 on 2018-01-31 14:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0066_auto_20180130_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='content',
            field=tinymce.models.HTMLField(max_length=65535),
        ),
    ]
