# Generated by Django 2.0.1 on 2018-01-31 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('content', '0067_auto_20180131_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buttoninmodule',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buttoninmodules', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icon',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageingallery',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imageingallerys', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listitems', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduleinpage',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moduleinpages', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoingallery',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videoingallerys', to='events.Event'),
            preserve_default=False,
        ),
    ]
