# Generated by Django 2.0.1 on 2018-02-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0069_auto_20180201_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
