# Generated by Django 2.0.1 on 2018-02-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0070_auto_20180201_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='videos_per_row',
            field=models.IntegerField(default=3),
        ),
    ]
