# Generated by Django 2.0.1 on 2018-02-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0071_videogallery_videos_per_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageingallery',
            old_name='gallery',
            new_name='imagegallery',
        ),
        migrations.RenameField(
            model_name='videoingallery',
            old_name='gallery',
            new_name='videogallery',
        ),
    ]
