# Generated by Django 2.0.1 on 2018-02-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_auto_20180206_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoingallery',
            name='caption',
        ),
        migrations.AddField(
            model_name='videoingallery',
            name='talk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.Talk'),
        ),
    ]
