# Generated by Django 2.0.1 on 2018-02-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_logo'),
        ('content', '0074_auto_20180215_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkInGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talkingallerys', to='events.Event')),
                ('talk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.Talk')),
                ('videogallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.VideoGallery')),
            ],
            options={
                'verbose_name_plural': 'Talks in gallery',
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='videoingallery',
            name='event',
        ),
        migrations.RemoveField(
            model_name='videoingallery',
            name='talk',
        ),
        migrations.RemoveField(
            model_name='videoingallery',
            name='videogallery',
        ),
        migrations.DeleteModel(
            name='VideoInGallery',
        ),
    ]
