# Generated by Django 2.0.1 on 2018-02-15 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0075_auto_20180215_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='public',
            field=models.BooleanField(default=True, help_text='If unchecked, only logged-in users can see this module'),
        ),
        migrations.AddField(
            model_name='page',
            name='public',
            field=models.BooleanField(default=True, help_text='If unchecked, only logged-in users can see this page'),
        ),
        migrations.AlterField(
            model_name='talkingallery',
            name='talk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='content.Talk'),
        ),
        migrations.AlterField(
            model_name='talkingallery',
            name='videogallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='content.VideoGallery'),
        ),
    ]
