# Generated by Django 2.0.1 on 2018-02-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0076_auto_20180215_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='event',
        ),
        migrations.RemoveField(
            model_name='room',
            name='event',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='event',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='event',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='language',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='room',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='talkingallery',
            name='event',
        ),
        migrations.RemoveField(
            model_name='talkingallery',
            name='talk',
        ),
        migrations.RemoveField(
            model_name='talkingallery',
            name='videogallery',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
        migrations.DeleteModel(
            name='TalkInGallery',
        ),
    ]
