# Generated by Django 2.0.1 on 2018-02-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0077_auto_20180219_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='event',
        ),
        migrations.RemoveField(
            model_name='buttoninmodule',
            name='event',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='event',
        ),
        migrations.RemoveField(
            model_name='imageingallery',
            name='event',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='event',
        ),
        migrations.RemoveField(
            model_name='module',
            name='event',
        ),
        migrations.RemoveField(
            model_name='moduleinpage',
            name='event',
        ),
        migrations.RemoveField(
            model_name='page',
            name='event',
        ),
        migrations.RemoveField(
            model_name='style',
            name='event',
        ),
    ]
