# Generated by Django 2.0.1 on 2018-02-19 19:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0078_auto_20180219_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHTML',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Module')),
                ('html_block', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Custom HTML blocks',
            },
            bases=('content.module',),
        ),
    ]
