# Generated by Django 2.0.1 on 2018-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0080_auto_20180219_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='images_per_row',
            field=models.IntegerField(default=3),
        ),
    ]
