# Generated by Django 2.0.1 on 2018-02-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0082_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGallery',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Module')),
            ],
            options={
                'verbose_name_plural': 'Post galleries',
            },
            bases=('content.module',),
        ),
        migrations.CreateModel(
            name='PostInGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postingallery', to='content.Post')),
                ('postgallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postingallery', to='content.PostGallery')),
            ],
            options={
                'verbose_name_plural': 'Posts in gallery',
            },
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('SPONSORSHIP', 'Sponsorship'), ('IMAGEGALLERY', 'Image gallery'), ('VIDEOGALLERY', 'Video gallery'), ('POSTS', 'Post gallery')], max_length=12, null=True),
        ),
    ]
