# Generated by Django 2.0.1 on 2018-02-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0083_auto_20180220_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='caca'),
            preserve_default=False,
        ),
    ]
