# Generated by Django 2.0.1 on 2018-02-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('content', '0085_auto_20180220_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostGallery',
            new_name='PostCategory',
        ),
        migrations.RemoveField(
            model_name='postingallery',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postingallery',
            name='postgallery',
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'Post categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='content.PostCategory'),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('SPONSORSHIP', 'Sponsorship'), ('IMAGEGALLERY', 'Image gallery'), ('VIDEOGALLERY', 'Video gallery'), ('POSTS', 'Post category')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='PostInGallery',
        ),
    ]
